name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install tools
        run: python -m pip install --upgrade pip pytest
        
      - name: Install pandas
        run: python -m pip install pandas
      
      - name: Install plotly
        run: python -m pip install plotly
        
      - name: Install matplotlib
        run: python -m pip install matplotlib
      
      - name: Install numpy
        run: python -m pip install numpy
        
      - name: Install sqlalchemy
        run: python -m pip install sqlalchemy
        
      - name: Install requests
        run: python -m pip install requests
        
      - name: Test with unittest
        run: |
          python3 -m unittest test.py